[workspace]
members = ["agent", "agent-ebpf", "xtask"]
resolver = "2"

[workspace.dependencies]
aya = { version = "0.12", features = ["async_tokio"] }
aya-bpf = "0.12"
tokio = { version = "1", features = ["full"] }
tonic = "0.11"
prost = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
