// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: sentinel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EXEC EventType = 0
	EventType_TCP  EventType = 1
	EventType_FILE EventType = 2
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EXEC",
		1: "TCP",
		2: "FILE",
	}
	EventType_value = map[string]int32{
		"EXEC": 0,
		"TCP":  1,
		"FILE": 2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_sentinel_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_sentinel_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{0}
}

type ExecEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          uint32                 `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Comm          string                 `protobuf:"bytes,3,opt,name=comm,proto3" json:"comm,omitempty"`
	Cmdline       string                 `protobuf:"bytes,4,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	Cwd           string                 `protobuf:"bytes,5,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Uid           uint32                 `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecEvent) Reset() {
	*x = ExecEvent{}
	mi := &file_sentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecEvent) ProtoMessage() {}

func (x *ExecEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecEvent.ProtoReflect.Descriptor instead.
func (*ExecEvent) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{0}
}

func (x *ExecEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ExecEvent) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ExecEvent) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *ExecEvent) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *ExecEvent) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecEvent) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type TcpEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Comm          string                 `protobuf:"bytes,2,opt,name=comm,proto3" json:"comm,omitempty"`
	SrcIp         string                 `protobuf:"bytes,3,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,4,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstIp         string                 `protobuf:"bytes,5,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstPort       uint32                 `protobuf:"varint,6,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Direction     string                 `protobuf:"bytes,7,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpEvent) Reset() {
	*x = TcpEvent{}
	mi := &file_sentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpEvent) ProtoMessage() {}

func (x *TcpEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpEvent.ProtoReflect.Descriptor instead.
func (*TcpEvent) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{1}
}

func (x *TcpEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *TcpEvent) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *TcpEvent) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *TcpEvent) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *TcpEvent) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *TcpEvent) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *TcpEvent) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type FileEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Comm          string                 `protobuf:"bytes,2,opt,name=comm,proto3" json:"comm,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Op            string                 `protobuf:"bytes,4,opt,name=op,proto3" json:"op,omitempty"`
	Ret           int32                  `protobuf:"varint,5,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEvent) Reset() {
	*x = FileEvent{}
	mi := &file_sentinel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEvent) ProtoMessage() {}

func (x *FileEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEvent.ProtoReflect.Descriptor instead.
func (*FileEvent) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{2}
}

func (x *FileEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *FileEvent) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *FileEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEvent) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *FileEvent) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type KernelEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	NodeId    string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type      EventType              `protobuf:"varint,4,opt,name=type,proto3,enum=sentinel.v1.EventType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*KernelEvent_Exec
	//	*KernelEvent_Tcp
	//	*KernelEvent_File
	Payload       isKernelEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelEvent) Reset() {
	*x = KernelEvent{}
	mi := &file_sentinel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelEvent) ProtoMessage() {}

func (x *KernelEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelEvent.ProtoReflect.Descriptor instead.
func (*KernelEvent) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{3}
}

func (x *KernelEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *KernelEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *KernelEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *KernelEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EXEC
}

func (x *KernelEvent) GetPayload() isKernelEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *KernelEvent) GetExec() *ExecEvent {
	if x != nil {
		if x, ok := x.Payload.(*KernelEvent_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *KernelEvent) GetTcp() *TcpEvent {
	if x != nil {
		if x, ok := x.Payload.(*KernelEvent_Tcp); ok {
			return x.Tcp
		}
	}
	return nil
}

func (x *KernelEvent) GetFile() *FileEvent {
	if x != nil {
		if x, ok := x.Payload.(*KernelEvent_File); ok {
			return x.File
		}
	}
	return nil
}

type isKernelEvent_Payload interface {
	isKernelEvent_Payload()
}

type KernelEvent_Exec struct {
	Exec *ExecEvent `protobuf:"bytes,10,opt,name=exec,proto3,oneof"`
}

type KernelEvent_Tcp struct {
	Tcp *TcpEvent `protobuf:"bytes,11,opt,name=tcp,proto3,oneof"`
}

type KernelEvent_File struct {
	File *FileEvent `protobuf:"bytes,12,opt,name=file,proto3,oneof"`
}

func (*KernelEvent_Exec) isKernelEvent_Payload() {}

func (*KernelEvent_Tcp) isKernelEvent_Payload() {}

func (*KernelEvent_File) isKernelEvent_Payload() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_sentinel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_sentinel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventAck) Reset() {
	*x = EventAck{}
	mi := &file_sentinel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventAck) ProtoMessage() {}

func (x *EventAck) ProtoReflect() protoreflect.Message {
	mi := &file_sentinel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventAck.ProtoReflect.Descriptor instead.
func (*EventAck) Descriptor() ([]byte, []int) {
	return file_sentinel_proto_rawDescGZIP(), []int{6}
}

func (x *EventAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_sentinel_proto protoreflect.FileDescriptor

const file_sentinel_proto_rawDesc = "" +
	"\n" +
	"\x0esentinel.proto\x12\vsentinel.v1\"\x83\x01\n" +
	"\tExecEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\rR\x04ppid\x12\x12\n" +
	"\x04comm\x18\x03 \x01(\tR\x04comm\x12\x18\n" +
	"\acmdline\x18\x04 \x01(\tR\acmdline\x12\x10\n" +
	"\x03cwd\x18\x05 \x01(\tR\x03cwd\x12\x10\n" +
	"\x03uid\x18\x06 \x01(\rR\x03uid\"\xb2\x01\n" +
	"\bTcpEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04comm\x18\x02 \x01(\tR\x04comm\x12\x15\n" +
	"\x06src_ip\x18\x03 \x01(\tR\x05srcIp\x12\x19\n" +
	"\bsrc_port\x18\x04 \x01(\rR\asrcPort\x12\x15\n" +
	"\x06dst_ip\x18\x05 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bdst_port\x18\x06 \x01(\rR\adstPort\x12\x1c\n" +
	"\tdirection\x18\a \x01(\tR\tdirection\"g\n" +
	"\tFileEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04comm\x18\x02 \x01(\tR\x04comm\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x0e\n" +
	"\x02op\x18\x04 \x01(\tR\x02op\x12\x10\n" +
	"\x03ret\x18\x05 \x01(\x05R\x03ret\"\x9d\x02\n" +
	"\vKernelEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12*\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.sentinel.v1.EventTypeR\x04type\x12,\n" +
	"\x04exec\x18\n" +
	" \x01(\v2\x16.sentinel.v1.ExecEventH\x00R\x04exec\x12)\n" +
	"\x03tcp\x18\v \x01(\v2\x15.sentinel.v1.TcpEventH\x00R\x03tcp\x12,\n" +
	"\x04file\x18\f \x01(\v2\x16.sentinel.v1.FileEventH\x00R\x04fileB\t\n" +
	"\apayload\"p\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"<\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1a\n" +
	"\bEventAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*(\n" +
	"\tEventType\x12\b\n" +
	"\x04EXEC\x10\x00\x12\a\n" +
	"\x03TCP\x10\x01\x12\b\n" +
	"\x04FILE\x10\x022\xa1\x01\n" +
	"\x11SentinelCollector\x12G\n" +
	"\bRegister\x12\x1c.sentinel.v1.RegisterRequest\x1a\x1d.sentinel.v1.RegisterResponse\x12C\n" +
	"\fStreamEvents\x12\x18.sentinel.v1.KernelEvent\x1a\x15.sentinel.v1.EventAck(\x010\x01B5Z3github.com/flipslidersand/sentinel-mesh/internal/pbb\x06proto3"

var (
	file_sentinel_proto_rawDescOnce sync.Once
	file_sentinel_proto_rawDescData []byte
)

func file_sentinel_proto_rawDescGZIP() []byte {
	file_sentinel_proto_rawDescOnce.Do(func() {
		file_sentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentinel_proto_rawDesc), len(file_sentinel_proto_rawDesc)))
	})
	return file_sentinel_proto_rawDescData
}

var file_sentinel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sentinel_proto_goTypes = []any{
	(EventType)(0),           // 0: sentinel.v1.EventType
	(*ExecEvent)(nil),        // 1: sentinel.v1.ExecEvent
	(*TcpEvent)(nil),         // 2: sentinel.v1.TcpEvent
	(*FileEvent)(nil),        // 3: sentinel.v1.FileEvent
	(*KernelEvent)(nil),      // 4: sentinel.v1.KernelEvent
	(*RegisterRequest)(nil),  // 5: sentinel.v1.RegisterRequest
	(*RegisterResponse)(nil), // 6: sentinel.v1.RegisterResponse
	(*EventAck)(nil),         // 7: sentinel.v1.EventAck
}
var file_sentinel_proto_depIdxs = []int32{
	0, // 0: sentinel.v1.KernelEvent.type:type_name -> sentinel.v1.EventType
	1, // 1: sentinel.v1.KernelEvent.exec:type_name -> sentinel.v1.ExecEvent
	2, // 2: sentinel.v1.KernelEvent.tcp:type_name -> sentinel.v1.TcpEvent
	3, // 3: sentinel.v1.KernelEvent.file:type_name -> sentinel.v1.FileEvent
	5, // 4: sentinel.v1.SentinelCollector.Register:input_type -> sentinel.v1.RegisterRequest
	4, // 5: sentinel.v1.SentinelCollector.StreamEvents:input_type -> sentinel.v1.KernelEvent
	6, // 6: sentinel.v1.SentinelCollector.Register:output_type -> sentinel.v1.RegisterResponse
	7, // 7: sentinel.v1.SentinelCollector.StreamEvents:output_type -> sentinel.v1.EventAck
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sentinel_proto_init() }
func file_sentinel_proto_init() {
	if File_sentinel_proto != nil {
		return
	}
	file_sentinel_proto_msgTypes[3].OneofWrappers = []any{
		(*KernelEvent_Exec)(nil),
		(*KernelEvent_Tcp)(nil),
		(*KernelEvent_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentinel_proto_rawDesc), len(file_sentinel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentinel_proto_goTypes,
		DependencyIndexes: file_sentinel_proto_depIdxs,
		EnumInfos:         file_sentinel_proto_enumTypes,
		MessageInfos:      file_sentinel_proto_msgTypes,
	}.Build()
	File_sentinel_proto = out.File
	file_sentinel_proto_goTypes = nil
	file_sentinel_proto_depIdxs = nil
}
