// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.0
// source: sentinel.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SentinelCollector_Register_FullMethodName     = "/sentinel.v1.SentinelCollector/Register"
	SentinelCollector_StreamEvents_FullMethodName = "/sentinel.v1.SentinelCollector/StreamEvents"
)

// SentinelCollectorClient is the client API for SentinelCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SentinelCollectorClient interface {
	// Agent registration (unary)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Bidirectional event stream: Agent sends KernelEvent, Collector acks
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[KernelEvent, EventAck], error)
}

type sentinelCollectorClient struct {
	cc grpc.ClientConnInterface
}

func NewSentinelCollectorClient(cc grpc.ClientConnInterface) SentinelCollectorClient {
	return &sentinelCollectorClient{cc}
}

func (c *sentinelCollectorClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, SentinelCollector_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentinelCollectorClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[KernelEvent, EventAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SentinelCollector_ServiceDesc.Streams[0], SentinelCollector_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[KernelEvent, EventAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SentinelCollector_StreamEventsClient = grpc.BidiStreamingClient[KernelEvent, EventAck]

// SentinelCollectorServer is the server API for SentinelCollector service.
// All implementations must embed UnimplementedSentinelCollectorServer
// for forward compatibility.
type SentinelCollectorServer interface {
	// Agent registration (unary)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Bidirectional event stream: Agent sends KernelEvent, Collector acks
	StreamEvents(grpc.BidiStreamingServer[KernelEvent, EventAck]) error
	mustEmbedUnimplementedSentinelCollectorServer()
}

// UnimplementedSentinelCollectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSentinelCollectorServer struct{}

func (UnimplementedSentinelCollectorServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedSentinelCollectorServer) StreamEvents(grpc.BidiStreamingServer[KernelEvent, EventAck]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedSentinelCollectorServer) mustEmbedUnimplementedSentinelCollectorServer() {}
func (UnimplementedSentinelCollectorServer) testEmbeddedByValue()                           {}

// UnsafeSentinelCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentinelCollectorServer will
// result in compilation errors.
type UnsafeSentinelCollectorServer interface {
	mustEmbedUnimplementedSentinelCollectorServer()
}

func RegisterSentinelCollectorServer(s grpc.ServiceRegistrar, srv SentinelCollectorServer) {
	// If the following call panics, it indicates UnimplementedSentinelCollectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SentinelCollector_ServiceDesc, srv)
}

func _SentinelCollector_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentinelCollectorServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentinelCollector_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentinelCollectorServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentinelCollector_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SentinelCollectorServer).StreamEvents(&grpc.GenericServerStream[KernelEvent, EventAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SentinelCollector_StreamEventsServer = grpc.BidiStreamingServer[KernelEvent, EventAck]

// SentinelCollector_ServiceDesc is the grpc.ServiceDesc for SentinelCollector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SentinelCollector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel.v1.SentinelCollector",
	HandlerType: (*SentinelCollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _SentinelCollector_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _SentinelCollector_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sentinel.proto",
}
